// <auto-generated />
using Korp.Inventory.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korp.Inventory.API.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260818201804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korp.Inventory.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10m,
                            Code = "000001",
                            Description = "CLP Siemens Simatic S7-1200 CPU 1214C",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 15m,
                            Code = "000002",
                            Description = "CLP WEG Clic-02 24VCC",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 8m,
                            Code = "000003",
                            Description = "Módulo de Expansão Digital Siemens SM 1223",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 5m,
                            Code = "000004",
                            Description = "IHM Siemens Simatic KTP700 Basic 7\"",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 6m,
                            Code = "000005",
                            Description = "IHM WEG cMT2078X 7\"",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 6,
                            Balance = 3m,
                            Code = "000006",
                            Description = "IHM Schneider Harmony ST6 10\"",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 7,
                            Balance = 12m,
                            Code = "000007",
                            Description = "Inversor de Frequência WEG CFW300 2cv 220V",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 8,
                            Balance = 8m,
                            Code = "000008",
                            Description = "Inversor de Frequência WEG CFW500 5cv 380V",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 9,
                            Balance = 5m,
                            Code = "000009",
                            Description = "Inversor de Frequência Siemens Sinamics G120C 3kW",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 10,
                            Balance = 7m,
                            Code = "000010",
                            Description = "Soft Starter WEG SSW07 17A 220-575V",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 11,
                            Balance = 25m,
                            Code = "000011",
                            Description = "Disjuntor Motor WEG MPW18 (4-6.3A)",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 12,
                            Balance = 20m,
                            Code = "000012",
                            Description = "Disjuntor Motor Schneider GV2ME14 (6-10A)",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 13,
                            Balance = 60m,
                            Code = "000013",
                            Description = "Disjuntor Termomagnético Siemens 5SL6 10A Unipolar",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 14,
                            Balance = 50m,
                            Code = "000014",
                            Description = "Disjuntor Miniatura MDW Curva C 16A Bipolar",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 15,
                            Balance = 40m,
                            Code = "000015",
                            Description = "Disjuntor Miniatura MDW Curva C 32A Tripolar",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 16,
                            Balance = 15m,
                            Code = "000016",
                            Description = "Interruptor Diferencial Residual (DR) 40A 30mA Tetrapolar",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 17,
                            Balance = 30m,
                            Code = "000017",
                            Description = "Dispositivo de Proteção contra Surtos (DPS) Clamper 275V 45kA",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 18,
                            Balance = 45m,
                            Code = "000018",
                            Description = "Contator Tripolar WEG CWM9-10 24VCC",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 19,
                            Balance = 35m,
                            Code = "000019",
                            Description = "Contator Tripolar WEG CWM25-10 220VCA",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 20,
                            Balance = 25m,
                            Code = "000020",
                            Description = "Contator Tripolar Schneider LC1D18 24VCC",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 21,
                            Balance = 50m,
                            Code = "000021",
                            Description = "Mini Contator WEG CWC07-10 24VCC",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 22,
                            Balance = 20m,
                            Code = "000022",
                            Description = "Relé de Sobrecarga Térmico WEG RW27-2D (7-10A)",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 23,
                            Balance = 18m,
                            Code = "000023",
                            Description = "Relé de Falta de Fase Altronic 220V",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 24,
                            Balance = 100m,
                            Code = "000024",
                            Description = "Relé de Interface Finder 24VCC 1NA/1NF",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 25,
                            Balance = 12m,
                            Code = "000025",
                            Description = "Relé de Estado Sólido (SSR) Novus 40A 24-280VCA",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 26,
                            Balance = 25m,
                            Code = "000026",
                            Description = "Relé Temporizador WEG RTW17 0-30s 24V/220V",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 27,
                            Balance = 30m,
                            Code = "000027",
                            Description = "Fonte de Alimentação Mean Well MDR-60-24 (24V 2.5A)",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 28,
                            Balance = 10m,
                            Code = "000028",
                            Description = "Fonte de Alimentação Siemens Sitop PSU100S 24V 10A",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 29,
                            Balance = 20m,
                            Code = "000029",
                            Description = "Fonte Chaveada WEG PSS24-W 24V 5A",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 30,
                            Balance = 80m,
                            Code = "000030",
                            Description = "Botão Pulsador Faceado Verde 22mm WEG",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 31,
                            Balance = 80m,
                            Code = "000031",
                            Description = "Botão Pulsador Faceado Vermelho 22mm WEG",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 32,
                            Balance = 40m,
                            Code = "000032",
                            Description = "Botão Cogumelo de Emergência com Trava 22mm",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 33,
                            Balance = 35m,
                            Code = "000033",
                            Description = "Chave Seletora 2 Posições Fixas 22mm",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 34,
                            Balance = 100m,
                            Code = "000034",
                            Description = "Sinaleiro LED Verde 24VCC 22mm",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 35,
                            Balance = 100m,
                            Code = "000035",
                            Description = "Sinaleiro LED Vermelho 220VCA 22mm",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 36,
                            Balance = 20m,
                            Code = "000036",
                            Description = "Sinaleiro Sonoro (Cigarra) 24VCC 22mm",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 37,
                            Balance = 45m,
                            Code = "000037",
                            Description = "Sensor Indutivo PNP M18 Faceado Sense",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 38,
                            Balance = 30m,
                            Code = "000038",
                            Description = "Sensor Indutivo NPN M12 Não-Faceado Novus",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 39,
                            Balance = 15m,
                            Code = "000039",
                            Description = "Sensor Capacitivo PNP M30 Autonics",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 40,
                            Balance = 12m,
                            Code = "000040",
                            Description = "Sensor Fotoelétrico Difuso 100mm Sick",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 41,
                            Balance = 25m,
                            Code = "000041",
                            Description = "Chave Fim de Curso Haste Flexível Metaltex",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 42,
                            Balance = 500m,
                            Code = "000042",
                            Description = "Borne de Passagem 2,5mm² Cinza WEG",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 43,
                            Balance = 200m,
                            Code = "000043",
                            Description = "Borne de Terra 4mm² Verde/Amarelo WEG",
                            Unit = "PC"
                        },
                        new
                        {
                            Id = 44,
                            Balance = 50m,
                            Code = "000044",
                            Description = "Trilho DIN 35mm x 7.5mm Perfurado (Barra 2m)",
                            Unit = "BR"
                        },
                        new
                        {
                            Id = 45,
                            Balance = 80m,
                            Code = "000045",
                            Description = "Canaleta Recortada Cinza 50x50mm (Barra 2m)",
                            Unit = "BR"
                        },
                        new
                        {
                            Id = 46,
                            Balance = 10m,
                            Code = "000046",
                            Description = "Cabo de Cobre Flexível 2,5mm² Preto (Rolo 100m)",
                            Unit = "RL"
                        },
                        new
                        {
                            Id = 47,
                            Balance = 15m,
                            Code = "000047",
                            Description = "Cabo de Cobre Flexível 1,5mm² Vermelho (Rolo 100m)",
                            Unit = "RL"
                        },
                        new
                        {
                            Id = 48,
                            Balance = 300m,
                            Code = "000048",
                            Description = "Cabo de Rede Industrial Blindado Cat6",
                            Unit = "M"
                        },
                        new
                        {
                            Id = 49,
                            Balance = 8m,
                            Code = "000049",
                            Description = "Switch Ethernet Industrial Não Gerenciável 5 Portas",
                            Unit = "UN"
                        },
                        new
                        {
                            Id = 50,
                            Balance = 5m,
                            Code = "000050",
                            Description = "Multímetro Digital Fluke 115",
                            Unit = "UN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
